               
时间： 2019-06-24 15:43:08.9563               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:08
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=1, Redelivered=False, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=ddf6cfa1-d4f3-4ed0-aa7f-4b50b6178be4, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjA4In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:09.1542               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:08
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=2, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=ddf6cfa1-d4f3-4ed0-aa7f-4b50b6178be4, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjA4In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:09.1860               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:08
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=3, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=ddf6cfa1-d4f3-4ed0-aa7f-4b50b6178be4, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjA4In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:09.2195               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:08
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=4, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=ddf6cfa1-d4f3-4ed0-aa7f-4b50b6178be4, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjA4In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:29.5483               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:29
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=6, Redelivered=False, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=aeb380da-9813-42d3-b4b6-04e2b08d0ead, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjI5In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:29.6346               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:29
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=7, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=aeb380da-9813-42d3-b4b6-04e2b08d0ead, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjI5In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:29.6711               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:29
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=8, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=aeb380da-9813-42d3-b4b6-04e2b08d0ead, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjI5In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:29.7182               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:29
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=9, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=aeb380da-9813-42d3-b4b6-04e2b08d0ead, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjI5In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:43:29.7494               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:43:29
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=10, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=aeb380da-9813-42d3-b4b6-04e2b08d0ead, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQzOjI5In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:44:49.5154               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:44:49
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=a6723c73-472a-46ed-ac62-fbbbe53aa0e6, DeliverTag=13, Redelivered=False, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=736f4885-c66f-4a31-96cc-0066640762f6, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQ0OjQ5In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:47:32.7854               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:47:16
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=920060b3-02f0-4d80-941f-1d11a039f3ad, DeliverTag=1, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=0214cf16-bb43-4a34-bf13-114288bdf287, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQ3OjE2In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:47:32.9265               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:47:16
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=920060b3-02f0-4d80-941f-1d11a039f3ad, DeliverTag=2, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=0214cf16-bb43-4a34-bf13-114288bdf287, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQ3OjE2In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:47:43.0159               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:47:33
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=920060b3-02f0-4d80-941f-1d11a039f3ad, DeliverTag=4, Redelivered=False, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=3dab4553-851b-40f1-a356-f8c74f53f919, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQ3OjMzIn0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 15:47:43.0754               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 15:47:33
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=920060b3-02f0-4d80-941f-1d11a039f3ad, DeliverTag=5, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=3dab4553-851b-40f1-a356-f8c74f53f919, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE1OjQ3OjMzIn0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 16:01:57.4779               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 16:01:57
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=fb8ae4d5-b987-461c-b433-9564d016cd44, DeliverTag=2, Redelivered=False, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=43170e1f-e289-4f87-9af1-541699ffd9de, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE2OjAxOjU3In0="               
               
-----------------------------------------------------------
               
时间： 2019-06-24 16:01:57.6116               
来源： EasyNetQ.Consumer.HandlerRunner+<InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
等级： Error               
堆栈：  HandlerRunner.InvokeUserMessageHandlerInternalAsync => AsyncMethodBuilderCore.Start => <InvokeUserMessageHandlerInternalAsync>d__4.MoveNext               
错误： System.Exception: Error Hanppened!   2019/6/24 16:01:57
   at RabbitmqMVCDemo.Services.MQService.<>c__DisplayClass5_0.<<HandleMessageAsync>b__0>d.MoveNext() in C:\Users\Gdky\Desktop\DotnetCoreDemo\01RabbitMQ\02EasyNetQ\9.补充Demo\9.2MVC实例（含DI、NLog、EasyNetQ）\RabbitmqMVCDemo\Services\MQService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)               
信息： Exception thrown by subscription callback, receivedInfo=[ConsumerTag=fb8ae4d5-b987-461c-b433-9564d016cd44, DeliverTag=3, Redelivered=True, Exchange=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, RoutingKey=, Queue=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo_subscribe_question], properties=ContentType=NULL, ContentEncoding=NULL, Headers=[], DeliveryMode=2, Priority=0, CorrelationId=43170e1f-e289-4f87-9af1-541699ffd9de, ReplyTo=NULL, Expiration=NULL, MessageId=NULL, Timestamp=0, Type=RabbitmqMVCDemo.Models.Question, RabbitmqMVCDemo, UserId=NULL, AppId=NULL, ClusterId=NULL, message="eyJUZXh0IjoiMjAxOS82LzI0IDE2OjAxOjU3In0="               
               
-----------------------------------------------------------
